### ISSUE TITLE
Bakgrunnur

### ISSUE THREAD

**Issue by JHT1609** [JHT1609/Leikjaforritun#1]
# Til að clipa
- [x] Múr Veggir
- [x] Múr Gólf
- [x] seinar og armor
- [x] hurðir og gates

## level hönunn á level/erfiðleika select
- [x] gólf
- [x] vegir
- [x] steinar og armor
- [x] hurðir og gates

## level hönunn á level 1
- [x] gólf
- [x] vegir
- [x] steinar og armor
- [x] hurðir og gates

## level hönunn á level 2
- [x] gólf
- [x] vegir
- [x] steinar og armor
- [x] hurðir og gates

## level hönunn á level 3
- [x] gólf
- [x] vegir
- [x] steinar og armor
- [x] hurðir og gates

**Comment by tumith** [comment]
búin með level 1 og 2 en þar að fin búsa síðustu hurðarnar

**Comment by tumith** [comment]
map búið en þarf að laga exit hurðirnar
