### ISSUE TITLE
Enemy AI (basic)

### ISSUE THREAD

**Issue by JHT1609** [JHT1609/Leikjaforritun#3]
- [x] Leiðar leiting
- [x] Reksturs Skynjari
- [x] Skaði
- [x] bak slá (Betra að geima þetta þvi það er mikil vægara að klára Player Controllerinn)

**Comment by tumith** [comment]
það væri flot ef örfarnar hverfa þegar þær snerta collider

**Comment by tumith** [comment]
er búin að reina að gera animaton en það er svoldið skrítið

**Comment by JHT1609** [comment]
droppum Bakslá
